---
title: "地域データの活用"
author: "Kotsubo Takuto"
date: "`r Sys.Date()`"
output:
  rmdformats::readthedown:
    code_folding: hide
    highlight: kate
    md_extensions: -ascii_identifiers
    toc_depth: 3
editor_options: 
  chunk_output_type: console
---

```{r knitr_init, echo=FALSE, cache=FALSE}
#rm(list=ls())
library(knitr)
library(rmdformats)

## Global options
options(max.print="75")
opts_chunk$set(echo=TRUE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```

```{r,echo=FALSE}
library(dplyr)
library(tidyverse)
library(rgl)
library(pipeR)
library(lubridate)
library(foreach)
```

# データの読み込み

必要なデータをSQLから読み込む

```{r source data,include=FALSE}
source('E:/git/DataCompetition/rmd/script/read_data.R', encoding = 'UTF-8')
ziocode <- read_csv('E:/git/DataCompetition/rmd/csv/zeocode_plus.csv')
```

```{r functions}
source('E:/git/DataCompetition/rmd/script/functions.R', encoding = 'UTF-8')
```


# データ補完

性別、誕生年についてランダムフォレストを用いて欠損値補完
その際、誕生年はカテゴリカルデータとして扱った

[ランダムフォレストによる欠損値補完](http://kato-kohaku-0.hatenablog.com/entry/2016/05/01/155908)

```{r}
#source('E:/git/DataCompetition/rmd/script/complement_data.R', encoding = 'UTF-8')
#write.csv(customer_com,'E:/git/DataCompetition/rmd/csv/customer_complicated.csv',fileEncoding = "cp932",quote=FALSE, row.names=FALSE)
customer_com <- read.csv('E:/git/DataCompetition/rmd/csv/customer_complicated.csv')
```

# 補完前のデータと補完後のデータを比較

補完前と補完後の性別および誕生年代のヒストグラムで概観を比較する

```{r 補完データ比較}
customer %>>% 
  ggplot(aes(x=sex)) + 
  geom_bar(fill="skyblue") +
  labs(title = "補完前",x = "性別",y = "人数") + 
  theme_bw() +
  theme(
    plot.title = element_text(hjust = 0.5),
    text = element_text(size = 15),
    panel.background = element_blank(),
    panel.grid = element_blank()
  )

customer_com %>>% 
  ggplot(aes(x=sex)) + 
  geom_bar(fill="skyblue") +
  labs(title = "補完後",x = "性別",y = "人数") + 
  theme_bw() +
  theme(
    plot.title = element_text(hjust = 0.5),
    text = element_text(size = 15),
    panel.background = element_blank(),
    panel.grid = element_blank()
  )  

customer %>>%
  ggplot(aes(x=birth_age %>% as.factor())) + 
  geom_bar(fill="skyblue") +
  labs(title = "補完前",x = "誕生年代",y = "人数") + 
  theme_bw() +
  theme(
    plot.title = element_text(hjust = 0.5),
    text = element_text(size = 15),
    panel.background = element_blank(),
    panel.grid = element_blank()
  )

customer_com %>>%
  ggplot(aes(x=birth_age %>% as.factor())) + 
  geom_bar(fill="skyblue") +
  labs(title = "補完後",x = "誕生年代",y = "人数") + 
  theme_bw() +
  theme(
    plot.title = element_text(hjust = 0.5),
    text = element_text(size = 15),
    panel.background = element_blank(),
    panel.grid = element_blank()
  )
```

```{r}
customer_com %>% 
  filter(zip_code > 1000000) %>% 
  left_join(ziocode, by="zip_code") %>% 
  left_join(store %>% 
              select(mode = store_id,store_lat = lat,store_long = long,station),by="mode") ->tmp
# 距離情報を追加
ans_dis <- foreach(a=tmp$lat,b=tmp$long,c=tmp$store_lat,d=tmp$store_long, .combine = "c") %do% distance_func_2(a,b,c,d) 
#ans2 <- foreach(a=tmp$lat,b=tmp$long,c=tmp$store_lat,d=tmp$store_long, .combine = "c") %do% theta_func(a,b,c,d) 
```

```{r 距離と諸データの関連性}
tmp %>% 
  mutate(distance = ans_dis) %>% 
  ggplot(aes(x= factor(station),y = distance)) +
  stat_summary(fun.y = mean, fun.ymin = min, 
               fun.ymax = max,colour = "deepskyblue") +
  labs(x = "店舗",y = "距離") +
  theme_bw() +
  theme(
  panel.background = element_blank(),
  panel.grid = element_blank()
  )

tmp %>%
  mutate(distance = ans_dis) %>% 
  filter(is.na(station) == FALSE) %>% 
  ggplot(aes(x=distance,y=visit_interval)) +
  geom_point(alpha = 0.2) +
  labs(x = "距離",y = "来店間隔") +
  facet_wrap("station") +
  theme_bw() +
  theme(
  panel.background = element_blank(),
  panel.grid = element_blank()
  )

tmp %>%
  mutate(distance = ans_dis) %>% 
  filter(is.na(station) == FALSE) %>% 
  ggplot(aes(x=distance,y=total_item_money)) +
  geom_point(alpha = 0.2) +
  labs(x = "距離",y = "店販購入金額") +
  facet_wrap("station") +
  theme_bw() +
  theme(
  panel.background = element_blank(),
  panel.grid = element_blank()
  )
```

