---
title: "sql read"
author: "kotsubotakuto"
date: "`r Sys.Date()`"
output:
  rmdformats::readthedown:
    code_folding: hide
    highlight: kate
    md_extensions: -ascii_identifiers
---
```{r option, echo=FALSE, cache=FALSE,warning=FALSE}
library(knitr)
library(rmdformats)
## Global options
options(max.print="75")
opts_chunk$set(echo=TRUE,
	             prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```

```{r,echo=FALSE}
library(DBI)  # 必須ではないらしい
library(RPostgreSQL)
library(dplyr)
```

```{r set databese,include=FALSE}
con <- dbConnect(PostgreSQL(), host="192.168.11.16", 
                 port=5432, 
                 dbname="datacom2017", 
                 user="postgres", 
                 password="postgres")

scan_query <- function(query_path) {
  return (
    scan(query_path, what='', quote='', sep='\n', comment.char = '', encoding='UTF-8') %>%
      gsub(pattern='--.*$', replacement='') %>% # 正規表現でコメントアウトを消す
      paste0(collapse=' ')
  )
  }
```

# データの読み込み

```{r}
dbGetQuery(con,"SET CLIENT_ENCODING TO 'shift-jis';")
store <- dbGetQuery(con,"SELECT * FROM store_1") %>% as.tbl()
staff <- dbGetQuery(con,"SELECT * FROM staff_1") %>% as.tbl()
line <- dbGetQuery(con,"SELECT * FROM line_henpin_syori_fin") %>% as.tbl()
receipt <- dbGetQuery(con,"SELECT * FROM receipt_henpin_syori_fin") %>% as.tbl()
customer <- dbGetQuery(con,"SELECT * FROM customer_3") %>% as.tbl()
```


```{r}
dbGetQuery(con,"SET CLIENT_ENCODING TO 'utf-8';")
product <- dbGetQuery(con,"SELECT * FROM product_2") %>% as.tbl()
product$product_category <- iconv(product$product_category,from = "utf-8",to="cp932")
product$category_1 <- iconv(product$category_1,from = "utf-8",to="cp932")
product$category_2 <- iconv(product$category_2,from = "utf-8",to="cp932")
product$product_name<- iconv(product$product_name,from = "utf-8",to="cp932")
```

# データ保存

```{r,eval=FALSE}
write.csv(customer_data, "csv/customer.csv", quote=FALSE, row.names=FALSE)
```

