---
title: "最終報告まとめ用"
author: "kotsubotakuto"
date: "2018年2月17日"
output: 
    html_document:
      md_extensions: -ascii_identifiers
      toc: true
      toc_depth: 3
---

```{r option, echo=FALSE, cache=FALSE, warning=FALSE}
library(knitr)
## Global options
options(max.print="75")
opts_chunk$set(echo=TRUE,
               cache = TRUE,
	             prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```

```{r,echo=FALSE}
library(dplyr)
library(tidyverse)
library(rgl)
library(pipeR)
library(lubridate)
library(modeest)
```

# 全データの読み込み

```{r read data}
source('E:/git/DataCompetition/script/read_data.R', encoding = 'UTF-8')
station_data <- read_csv("csv/station_customer.csv")
```


```{r}
station_data %>% 
  left_join(customer,by = "customer_id") %>% 
  group_by(customer_id,m) %>% 
  summarise(tmp = mean(visit_interval,na.rm = TRUE)) %>% 
  ungroup() %>% 
  group_by(m) %>% 
  summarise(tmp = mean(tmp,na.rm = TRUE),
            counter = n()) %>% 
  na.omit() %>% 
  arrange(desc(tmp)) %>>% 
  (? head(.,20)) %>>%
  tail(20)
```


```{r}
receipt %>% 
  select(cs_point == 1) %>% 
  summarise()
```









